name = "Project4"
uuid = "ecc53ea5-793d-4987-87f3-cc5cc30d7aac"
authors = ["Alphonsus Adu-Bredu"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
